### ISSUE TITLE
Listing all leaf types

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/sciline#183]
## Context
I removed a leaf type to remove unnecessary step in a workflow and then user (Christian in this case) had no idea which type to visualize/compute.

It'll be easier for users if there is an interface in sciline as well to list all the leaf nodes,
and then it can be used for visualization without any type specified,
and for workflow widgets.

## Related Issues
- https://github.com/scipp/sciline/issues/177
- https://github.com/scipp/essreduce/issues/28

## Implementation Examples
There is an example already in `essreduce`.
https://github.com/scipp/essreduce/blob/aef4a3c1094dd15f1849aedc74e9960e1b922de3/src/ess/reduce/workflow.py#L52-L57

## TODO

 - [ ] Implement an interface that list all leaf nodes in the workflow
 - [ ] Use the interface for `visualize` without any arguments
 - [ ] Include the leaf nodes as examples in the `KeyError` or `NoProviderFound` error message.
